name: ci

on:
  push:
    branches:
      - main
      - master
      - dev
      - develop
      - development
      - release
  workflow_dispatch:

jobs:
  build:
    env:
      PROJECT_NAME: iac-aws-rds-serverless
      AWS_REGION: us-east-1
      REMOTE_STATE_BUCKET: rocketseat-terraform-remote-state
      REMOTE_STATE_FILE: iac-aws-rds-serverless-ecr.tfstate
      REMOTE_STATE_AWS_REGION: us-east-1
      PRODUCT: iac
      CREATED_BY: devops-tools
      OWNER: squad-rocketseat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: configure-crentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: test
        run: chmod +x ./devops/scripts/test.sh && ./devops/scripts/test.sh

      - name: build
        run: chmod +x ./devops/scripts/build.sh && ./devops/scripts/build.sh
